services:
  - type: web
    name: diet-planner-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GRQ_API_KEY
        sync: false
      - key: PORT
        value: 10000
